server {
    listen 80;
    server_name _;
 
    root /usr/share/nginx/html;
    index index.html;
    proxy_buffer_size  128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    large_client_header_buffers 4 16k;
    client_header_buffer_size 16k;
    
 
    # Auth routes
    location /auth/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Cookie $http_cookie;
        
        proxy_buffer_size  128k;
        proxy_buffers 4 256k;
    }
 
    # Users routes
    location /users/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Cookie $http_cookie;
        
        proxy_buffer_size  128k;
        proxy_buffers 4 256k;
    }
 
    # Events routes
    location /events/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Cookie $http_cookie;
        
        proxy_buffer_size  128k;
        proxy_buffers 4 256k;
    }
    
    location /events {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Cookie $http_cookie;
        
        proxy_buffer_size  128k;
        proxy_buffers 4 256k;
    }
    # Organizer routes
    location /organizer/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Cookie $http_cookie;
        
        proxy_buffer_size  128k;
        proxy_buffers 4 256k;
    }
 
    # React app — must be last
    location / {
        try_files $uri $uri/ /index.html;
    }
}
